export const categories = [
  {
    id: "1",
    title: "Kinh Qur'an và kiến thức",
    hadeeths_count: "6",
    parent_id: null,
  },
  {
    id: "2",
    title: "Hadith và kiến thức",
    hadeeths_count: "1",
    parent_id: null,
  },
  {
    id: "3",
    title: "Giáo lý đức tin",
    hadeeths_count: "88",
    parent_id: null,
  },
  {
    id: "4",
    title: "Giáo luật thực hành và bằng chứng",
    hadeeths_count: "216",
    parent_id: null,
  },
  {
    id: "5",
    title: "Ân phúc và lễ nghĩa",
    hadeeths_count: "237",
    parent_id: null,
  },
  {
    id: "6",
    title: "Tuyên truyền",
    hadeeths_count: "23",
    parent_id: null,
  },
  {
    id: "7",
    title: "Tiểu sử và lịch sử",
    hadeeths_count: "40",
    parent_id: null,
  },
  {
    id: "10",
    title: "Giảng giải nội dung ý nghĩa Qur'an",
    hadeeths_count: "1",
    parent_id: "1",
  },
  {
    id: "11",
    title: "Các nghiên cứu chung về Kinh Qur'an",
    hadeeths_count: "3",
    parent_id: "1",
  },
  {
    id: "12",
    title: "Các ân phúc của Kinh Qur'an",
    hadeeths_count: "2",
    parent_id: "1",
  },
  {
    id: "29",
    title: "Các giáo luật về Qur'an và quyển Qur'an",
    hadeeths_count: "2",
    parent_id: "11",
  },
  {
    id: "31",
    title: "Lễ nghĩa xướng đọc và mang xách Qur'an",
    hadeeths_count: "1",
    parent_id: "11",
  },
  {
    id: "39",
    title: "Ân phúc của việc quan tâm đến Kinh Qur'an",
    hadeeths_count: "1",
    parent_id: "12",
  },
  {
    id: "40",
    title: "Ân phúc các chương và các câu của Qur'an",
    hadeeths_count: "1",
    parent_id: "12",
  },
  {
    id: "44",
    title: "Các nghiên cứu chung về Sunnah",
    hadeeths_count: "1",
    parent_id: "2",
  },
  {
    id: "56",
    title: "Vai trò và tầm quan trọng của Sunnah",
    hadeeths_count: "1",
    parent_id: "44",
  },
  {
    id: "59",
    title: "Đức tin nơi Allah Toàn Năng",
    hadeeths_count: "40",
    parent_id: "3",
  },
  {
    id: "60",
    title: "Đức tin nơi các Thiên Thần",
    hadeeths_count: "3",
    parent_id: "3",
  },
  {
    id: "61",
    title: "Đức tin nơi các Kinh Sách",
    hadeeths_count: "1",
    parent_id: "3",
  },
  {
    id: "62",
    title: "Đức tin nơi các Thiên Sứ",
    hadeeths_count: "8",
    parent_id: "3",
  },
  {
    id: "63",
    title: "Đức tin nơi Đời Sau",
    hadeeths_count: "24",
    parent_id: "3",
  },
  {
    id: "64",
    title: "Đức tin nơi sự tiền định",
    hadeeths_count: "5",
    parent_id: "3",
  },
  {
    id: "65",
    title: "Tên gọi và giáo luật",
    hadeeths_count: "6",
    parent_id: "3",
  },
  {
    id: "66",
    title: "Sahabah (những vị đồng hành của Thiên Sứ Muhammad)",
    hadeeths_count: "3",
    parent_id: "3",
  },
  {
    id: "68",
    title: "Bạn và địch",
    hadeeths_count: "2",
    parent_id: "3",
  },
  {
    id: "71",
    title: "Nhóm và trường phái",
    hadeeths_count: "1",
    parent_id: "3",
  },
  {
    id: "72",
    title: "Giáo lý độc thần về hành động của Allah",
    hadeeths_count: "1",
    parent_id: "59",
  },
  {
    id: "73",
    title: "Giáo lý độc thần về thờ phượng Allah",
    hadeeths_count: "7",
    parent_id: "59",
  },
  {
    id: "74",
    title: "Giáo lý độc thần về các tên gọi và thuộc tính của Allah",
    hadeeths_count: "32",
    parent_id: "59",
  },
  {
    id: "75",
    title: "Thiên Thần",
    hadeeths_count: "1",
    parent_id: "60",
  },
  {
    id: "80",
    title:
      "Các vị Nabi, các vị Thiên Sứ của những thời đại trước - cầu xin Allah ban phúc lành cho Họ",
    hadeeths_count: "5",
    parent_id: "62",
  },
  {
    id: "81",
    title:
      "Nabi của chúng ta, Muhammad - cầu xin Allah ban bình an và phúc lành cho Người -",
    hadeeths_count: "2",
    parent_id: "62",
  },
  {
    id: "82",
    title: "Các vinh dự của người Wali",
    hadeeths_count: "1",
    parent_id: "62",
  },
  {
    id: "83",
    title: "Cuộc sống nơi cõi Barzakh (cõi chết, hay cõi mộ)",
    hadeeths_count: "2",
    parent_id: "63",
  },
  {
    id: "84",
    title: "Các dấu hiệu báo trước của Ngày Tận Thế",
    hadeeths_count: "3",
    parent_id: "63",
  },
  {
    id: "85",
    title: "Cuộc sống Đời Sau",
    hadeeths_count: "15",
    parent_id: "63",
  },
  {
    id: "86",
    title: "Các cấp bậc về tiền định",
    hadeeths_count: "2",
    parent_id: "64",
  },
  {
    id: "87",
    title: "Các vấn đề liên quan đến sự tiền định",
    hadeeths_count: "2",
    parent_id: "64",
  },
  {
    id: "88",
    title: "Islam",
    hadeeths_count: "1",
    parent_id: "65",
  },
  {
    id: "92",
    title: "Sự tăng giảm của đức tin",
    hadeeths_count: "2",
    parent_id: "65",
  },
  {
    id: "94",
    title: "Các phần của đức tin",
    hadeeths_count: "1",
    parent_id: "65",
  },
  {
    id: "97",
    title: "Shirk (tổ hợp các thần linh cùng với Allah)",
    hadeeths_count: "2",
    parent_id: "65",
  },
  {
    id: "101",
    title: "Ân phúc của Sahabah - cầu xin Allah hài lòng về họ -",
    hadeeths_count: "3",
    parent_id: "66",
  },
  {
    id: "109",
    title: "Giáo luật về đồng minh và kẻ thù",
    hadeeths_count: "1",
    parent_id: "68",
  },
  {
    id: "110",
    title: "Sự bắt chước không được phép",
    hadeeths_count: "1",
    parent_id: "68",
  },
  {
    id: "119",
    title: "Sự phát triển của các nhóm và trường phái cổ xưa",
    hadeeths_count: "1",
    parent_id: "71",
  },
  {
    id: "121",
    title: "Giáo luật thực hành về thờ phượng",
    hadeeths_count: "162",
    parent_id: "4",
  },
  {
    id: "122",
    title: "Giáo luật thực hành về quan hệ xã hội",
    hadeeths_count: "17",
    parent_id: "4",
  },
  {
    id: "123",
    title: "Giáo luật phân chia tài sản thừa kế",
    hadeeths_count: "1",
    parent_id: "4",
  },
  {
    id: "124",
    title: "Giáo luật thực hành về hôn nhân gia đình",
    hadeeths_count: "20",
    parent_id: "4",
  },
  {
    id: "125",
    title: "Thuốc, cách chữa trị và lời niệm chú được phép",
    hadeeths_count: "7",
    parent_id: "4",
  },
  {
    id: "126",
    title: "Thức ăn, đồ uống",
    hadeeths_count: "9",
    parent_id: "4",
  },
  {
    id: "128",
    title: "Các bản án phạt",
    hadeeths_count: "4",
    parent_id: "4",
  },
  {
    id: "132",
    title: "Usul Al-Fiqh",
    hadeeths_count: "3",
    parent_id: "4",
  },
  {
    id: "133",
    title: "Tẩy rửa",
    hadeeths_count: "59",
    parent_id: "121",
  },
  {
    id: "134",
    title: "Salah",
    hadeeths_count: "40",
    parent_id: "121",
  },
  {
    id: "135",
    title: "An táng",
    hadeeths_count: "9",
    parent_id: "121",
  },
  {
    id: "136",
    title: "Zakah",
    hadeeths_count: "17",
    parent_id: "121",
  },
  {
    id: "137",
    title: "Nhịn chay",
    hadeeths_count: "5",
    parent_id: "121",
  },
  {
    id: "138",
    title: "Hành hương Hajj và 'Umrah",
    hadeeths_count: "15",
    parent_id: "121",
  },
  {
    id: "139",
    title: "Đấu tranh vì chính nghĩa của Allah",
    hadeeths_count: "21",
    parent_id: "121",
  },
  {
    id: "140",
    title: "Mua bán, kinh doanh",
    hadeeths_count: "1",
    parent_id: "122",
  },
  {
    id: "148",
    title: "Bảo hành và đảm bảo",
    hadeeths_count: "1",
    parent_id: "122",
  },
  {
    id: "150",
    title: "Hoà giải và các giáo luật về xóm giềng",
    hadeeths_count: "1",
    parent_id: "122",
  },
  {
    id: "153",
    title: "Công ty",
    hadeeths_count: "1",
    parent_id: "122",
  },
  {
    id: "164",
    title: "Hiến",
    hadeeths_count: "1",
    parent_id: "122",
  },
  {
    id: "165",
    title: "Cho và biếu tặng",
    hadeeths_count: "1",
    parent_id: "122",
  },
  {
    id: "166",
    title: "Di chúc",
    hadeeths_count: "1",
    parent_id: "122",
  },
  {
    id: "167",
    title: "Phóng thích nô lệ",
    hadeeths_count: "4",
    parent_id: "122",
  },
  {
    id: "169",
    title: "Thề, nguyện",
    hadeeths_count: "6",
    parent_id: "122",
  },
  {
    id: "174",
    title: "Các rào cản thừa kế",
    hadeeths_count: "1",
    parent_id: "123",
  },
  {
    id: "191",
    title: "Kết hôn",
    hadeeths_count: "3",
    parent_id: "124",
  },
  {
    id: "192",
    title: "Li hôn",
    hadeeths_count: "1",
    parent_id: "124",
  },
  {
    id: "197",
    title: "Li'an",
    hadeeths_count: "2",
    parent_id: "124",
  },
  {
    id: "198",
    title: "Iddah (thời gian ở vậy)",
    hadeeths_count: "1",
    parent_id: "124",
  },
  {
    id: "201",
    title: "Các loại cấp dưỡng",
    hadeeths_count: "3",
    parent_id: "124",
  },
  {
    id: "202",
    title: "Ăn mặc và làm đẹp",
    hadeeths_count: "2",
    parent_id: "124",
  },
  {
    id: "204",
    title: "Xã hội Muslim",
    hadeeths_count: "2",
    parent_id: "124",
  },
  {
    id: "205",
    title: "Giáo luật về phụ nữ",
    hadeeths_count: "6",
    parent_id: "124",
  },
  {
    id: "207",
    title: "Phương thuốc trị bệnh theo cách của Nabi",
    hadeeths_count: "3",
    parent_id: "125",
  },
  {
    id: "211",
    title: "Lời niệm chú được phép",
    hadeeths_count: "3",
    parent_id: "125",
  },
  {
    id: "212",
    title: "Giáo luật về thức ăn, đồ uống",
    hadeeths_count: "1",
    parent_id: "126",
  },
  {
    id: "213",
    title: "Động vật và chim chóc được phép và không được phép ăn",
    hadeeths_count: "5",
    parent_id: "126",
  },
  {
    id: "215",
    title: "Cắt tiết",
    hadeeths_count: "1",
    parent_id: "126",
  },
  {
    id: "216",
    title: "Săn bắn",
    hadeeths_count: "1",
    parent_id: "126",
  },
  {
    id: "218",
    title: "Những đồ uống không được phép",
    hadeeths_count: "1",
    parent_id: "126",
  },
  {
    id: "224",
    title: "Án phạt tội Zina",
    hadeeths_count: "2",
    parent_id: "128",
  },
  {
    id: "226",
    title: "Án phạt tội uống rượu",
    hadeeths_count: "2",
    parent_id: "128",
  },
  {
    id: "249",
    title: "Luật được qui định trong Islam",
    hadeeths_count: "1",
    parent_id: "132",
  },
  {
    id: "253",
    title: "Kinh Sách (Qur'an)",
    hadeeths_count: "1",
    parent_id: "132",
  },
  {
    id: "262",
    title: "Các mục đích của luật Shari'ah",
    hadeeths_count: "1",
    parent_id: "132",
  },
  {
    id: "265",
    title: "Các ân phúc",
    hadeeths_count: "46",
    parent_id: "5",
  },
  {
    id: "266",
    title: "Giáo luật thực hành về đạo đức",
    hadeeths_count: "54",
    parent_id: "5",
  },
  {
    id: "267",
    title: "Các nghi thức pháp lý",
    hadeeths_count: "56",
    parent_id: "5",
  },
  {
    id: "268",
    title: "Giáo luật thực hành về việc cầu nguyện và tụng niệm",
    hadeeths_count: "31",
    parent_id: "5",
  },
  {
    id: "269",
    title: "Lời khuyên răn",
    hadeeths_count: "64",
    parent_id: "5",
  },
  {
    id: "270",
    title: "Ân phúc của kiến thức",
    hadeeths_count: "1",
    parent_id: "265",
  },
  {
    id: "271",
    title: "Ân phúc của thuyết độc thần",
    hadeeths_count: "3",
    parent_id: "265",
  },
  {
    id: "272",
    title: "Ân phúc của Kinh Qur'an",
    hadeeths_count: "1",
    parent_id: "265",
  },
  {
    id: "273",
    title: "Ân phúc của việc hiếu thảo với cha mẹ",
    hadeeths_count: "3",
    parent_id: "265",
  },
  {
    id: "274",
    title: "Ân phúc của việc hàn gắn dòng tộc",
    hadeeths_count: "2",
    parent_id: "265",
  },
  {
    id: "275",
    title: "Ân phúc của gia quyến Thiên Sứ - cầu xin Allah hài lòng về họ -",
    hadeeths_count: "1",
    parent_id: "265",
  },
  {
    id: "276",
    title: "Ân phúc của Sahabah - cầu xin Allah hài lòng về họ -",
    hadeeths_count: "6",
    parent_id: "265",
  },
  {
    id: "277",
    title: "Ân phúc của việc hành thiện",
    hadeeths_count: "14",
    parent_id: "265",
  },
  {
    id: "278",
    title: "Ân phúc của việc tụng niệm",
    hadeeths_count: "6",
    parent_id: "265",
  },
  {
    id: "279",
    title: "Ân phúc của việc cầu nguyện",
    hadeeths_count: "1",
    parent_id: "265",
  },
  {
    id: "280",
    title: "Ân phúc hành động của nội tâm",
    hadeeths_count: "5",
    parent_id: "265",
  },
  {
    id: "281",
    title: "Ân phúc hành động của thể xác",
    hadeeths_count: "3",
    parent_id: "265",
  },
  {
    id: "282",
    title: "Các đức tính đáng khen",
    hadeeths_count: "40",
    parent_id: "266",
  },
  {
    id: "283",
    title: "Những bản tính đáng trách",
    hadeeths_count: "14",
    parent_id: "266",
  },
  {
    id: "284",
    title: "Lễ nghĩa của thầy và trò",
    hadeeths_count: "2",
    parent_id: "267",
  },
  {
    id: "286",
    title: "Lễ nghĩa chào Salam và xin phép",
    hadeeths_count: "7",
    parent_id: "267",
  },
  {
    id: "287",
    title: "Lễ nghĩa nói năng và im lặng",
    hadeeths_count: "11",
    parent_id: "267",
  },
  {
    id: "290",
    title: "Phép lịch sự trong ăn uống",
    hadeeths_count: "7",
    parent_id: "267",
  },
  {
    id: "292",
    title: "Lễ nghĩa và giáo luật về việc đi đường xa",
    hadeeths_count: "13",
    parent_id: "267",
  },
  {
    id: "293",
    title: "Lễ nghĩa khi ngủ và thức dậy",
    hadeeths_count: "2",
    parent_id: "267",
  },
  {
    id: "294",
    title: "Lễ nghĩa khi nằm mộng",
    hadeeths_count: "6",
    parent_id: "267",
  },
  {
    id: "295",
    title: "Lễ nghĩa thăm viếng và xin phép",
    hadeeths_count: "3",
    parent_id: "267",
  },
  {
    id: "296",
    title: "Lễ nghĩa hắt hơi và ngáp",
    hadeeths_count: "1",
    parent_id: "267",
  },
  {
    id: "297",
    title: "Văn hoá thăm viếng người bệnh",
    hadeeths_count: "2",
    parent_id: "267",
  },
  {
    id: "298",
    title: "Cách ăn mặc",
    hadeeths_count: "1",
    parent_id: "267",
  },
  {
    id: "299",
    title:
      "Sự hướng dẫn của Nabi - cầu xin Allah ban bình an và phúc lành cho Người - về tụng niệm",
    hadeeths_count: "2",
    parent_id: "268",
  },
  {
    id: "300",
    title: "Lợi ích của việc tụng niệm Allah Toàn Năng",
    hadeeths_count: "3",
    parent_id: "268",
  },
  {
    id: "301",
    title: "Các lời tụng niệm sáng chiều",
    hadeeths_count: "1",
    parent_id: "268",
  },
  {
    id: "302",
    title: "Các lời tụng niệm không giới hạn",
    hadeeths_count: "4",
    parent_id: "268",
  },
  {
    id: "303",
    title: "Các lời tụng niệm khi vào và ra khỏi nhà",
    hadeeths_count: "1",
    parent_id: "268",
  },
  {
    id: "307",
    title: "Các lời tụng niệm vào các thời điểm khó khăn",
    hadeeths_count: "2",
    parent_id: "268",
  },
  {
    id: "308",
    title: "Các lời tụng niệm khi có chuyện bất an",
    hadeeths_count: "2",
    parent_id: "268",
  },
  {
    id: "309",
    title: "Giáo luật về cầu nguyện",
    hadeeths_count: "2",
    parent_id: "268",
  },
  {
    id: "310",
    title: "Các dạng cầu nguyện",
    hadeeths_count: "1",
    parent_id: "268",
  },
  {
    id: "311",
    title: "Lễ nghĩa khi cầu nguyện",
    hadeeths_count: "3",
    parent_id: "268",
  },
  {
    id: "312",
    title:
      "Những điều giúp lời cầu xin được chấp nhận và những nguyên nhân làm cho nó bị khước từ",
    hadeeths_count: "4",
    parent_id: "268",
  },
  {
    id: "313",
    title: "Những lời cầu nguyện theo mẫu có sẵn",
    hadeeths_count: "9",
    parent_id: "268",
  },
  {
    id: "314",
    title: "Hành động của nội tâm",
    hadeeths_count: "7",
    parent_id: "269",
  },
  {
    id: "315",
    title: "Các loại tâm bệnh",
    hadeeths_count: "1",
    parent_id: "269",
  },
  {
    id: "316",
    title: "Giản dị và mộ đạo",
    hadeeths_count: "6",
    parent_id: "269",
  },
  {
    id: "317",
    title: "Tình trạng của người đức hạnh",
    hadeeths_count: "6",
    parent_id: "269",
  },
  {
    id: "318",
    title: "Lên án tội lỗi",
    hadeeths_count: "4",
    parent_id: "269",
  },
  {
    id: "319",
    title: "Xem thường việc ham mê trần gian",
    hadeeths_count: "13",
    parent_id: "269",
  },
  {
    id: "321",
    title: "Sám hối",
    hadeeths_count: "2",
    parent_id: "269",
  },
  {
    id: "322",
    title: "Thanh lọc bản thân",
    hadeeths_count: "1",
    parent_id: "269",
  },
  {
    id: "323",
    title: "Sự kinh hoàng nơi cõi mộ",
    hadeeths_count: "1",
    parent_id: "269",
  },
  {
    id: "324",
    title: "Mô tả Thiên Đàng và Hoả Ngục",
    hadeeths_count: "26",
    parent_id: "269",
  },
  {
    id: "325",
    title: "Mời gọi đến với Allah",
    hadeeths_count: "7",
    parent_id: "6",
  },
  {
    id: "326",
    title: "Bảo ban hành thiện và ngăn điều xấu",
    hadeeths_count: "2",
    parent_id: "6",
  },
  {
    id: "327",
    title: "Chính trị Islam",
    hadeeths_count: "15",
    parent_id: "6",
  },
  {
    id: "338",
    title: "Ân phúc và sự tốt đẹp của Islam",
    hadeeths_count: "4",
    parent_id: "325",
  },
  {
    id: "340",
    title: "Nhân quyền trong Islam",
    hadeeths_count: "1",
    parent_id: "325",
  },
  {
    id: "341",
    title: "Quyền của động vật trong Islam",
    hadeeths_count: "4",
    parent_id: "325",
  },
  {
    id: "345",
    title: "Ân phúc việc bảo ban hành thiện và ngăn điều xấu",
    hadeeths_count: "1",
    parent_id: "326",
  },
  {
    id: "348",
    title: "Điều kiện cần có cho việc bảo ban hành thiện và ngăn điều xấu",
    hadeeths_count: "1",
    parent_id: "326",
  },
  {
    id: "352",
    title: "Các nhiệm vụ của lãnh đạo",
    hadeeths_count: "3",
    parent_id: "327",
  },
  {
    id: "353",
    title: "Quyền hạn của lãnh đạo đối với dân chúng",
    hadeeths_count: "10",
    parent_id: "327",
  },
  {
    id: "367",
    title: "Tiểu sử Thiên Sứ Muhammad",
    hadeeths_count: "35",
    parent_id: "7",
  },
  {
    id: "368",
    title: "Lịch sử",
    hadeeths_count: "5",
    parent_id: "7",
  },
  {
    id: "392",
    title:
      "Những người vợ của Thiên Sứ Muhammad - cầu xin Allah ban bình an và phúc lành cho Người - và tình trạng cuộc sống của Thiên Sứ",
    hadeeths_count: "2",
    parent_id: "367",
  },
  {
    id: "397",
    title:
      "Sự cống hiến của Thiên Sứ Muhammad - cầu xin Allah ban bình an và phúc lành cho Người -",
    hadeeths_count: "1",
    parent_id: "367",
  },
  {
    id: "400",
    title: "Kỷ nguyên Makkah",
    hadeeths_count: "2",
    parent_id: "367",
  },
  {
    id: "403",
    title: "Các cuộc chinh phục và gửi quân xuất chinh của Thiên Sứ",
    hadeeths_count: "8",
    parent_id: "367",
  },
  {
    id: "405",
    title:
      "Cái chết của Thiên Sứ Muhammad - cầu xin Allah ban bình an và phúc lành cho Người -",
    hadeeths_count: "2",
    parent_id: "367",
  },
  {
    id: "406",
    title: "Các phẩm chất đáng ca ngợi",
    hadeeths_count: "19",
    parent_id: "367",
  },
  {
    id: "407",
    title: "Câu chuyện và hoàn cảnh của các cộng đồng thời trước",
    hadeeths_count: "3",
    parent_id: "368",
  },
  {
    id: "413",
    title: "Cuộc đời và tiểu sử của các nhân vật",
    hadeeths_count: "1",
    parent_id: "368",
  },
  {
    id: "415",
    title: "Các dịp lễ định kỳ",
    hadeeths_count: "1",
    parent_id: "368",
  },
  {
    id: "431",
    title: "Giáo luật về nước",
    hadeeths_count: "6",
    parent_id: "133",
  },
  {
    id: "432",
    title: "Tẩy sạch Najis",
    hadeeths_count: "9",
    parent_id: "133",
  },
  {
    id: "434",
    title: "Vật dụng",
    hadeeths_count: "4",
    parent_id: "133",
  },
  {
    id: "435",
    title: "Phép tắc đi vệ sinh",
    hadeeths_count: "4",
    parent_id: "133",
  },
  {
    id: "436",
    title: "Sunnah Fit-rah",
    hadeeths_count: "4",
    parent_id: "133",
  },
  {
    id: "437",
    title: "Wudu'",
    hadeeths_count: "23",
    parent_id: "133",
  },
  {
    id: "438",
    title: "Tắm",
    hadeeths_count: "7",
    parent_id: "133",
  },
  {
    id: "439",
    title: "Tayammum",
    hadeeths_count: "2",
    parent_id: "133",
  },
  {
    id: "440",
    title: "Kinh nguyệt, hậu sản và rong kinh",
    hadeeths_count: "4",
    parent_id: "133",
  },
  {
    id: "442",
    title: "Các trụ cột của Wudu'",
    hadeeths_count: "1",
    parent_id: "437",
  },
  {
    id: "443",
    title: "Các nghi thức khuyến khích và lễ nghĩa của Wudu'",
    hadeeths_count: "6",
    parent_id: "437",
  },
  {
    id: "444",
    title: "Cách thức Wudu'",
    hadeeths_count: "7",
    parent_id: "437",
  },
  {
    id: "445",
    title: "Những điều làm hư Wudu'",
    hadeeths_count: "7",
    parent_id: "437",
  },
  {
    id: "456",
    title:
      "Tính bắt buộc của lễ nguyện Salah và giáo luật về người bỏ lễ nguyện Salah",
    hadeeths_count: "1",
    parent_id: "134",
  },
  {
    id: "457",
    title: "Ân phúc của lễ nguyện Salah",
    hadeeths_count: "3",
    parent_id: "134",
  },
  {
    id: "458",
    title: "Azdan và Iqamah",
    hadeeths_count: "4",
    parent_id: "134",
  },
  {
    id: "459",
    title: "Các giờ cấm lễ nguyện Salah",
    hadeeths_count: "1",
    parent_id: "134",
  },
  {
    id: "460",
    title: "Các điều kiện cần của lễ nguyện Salah",
    hadeeths_count: "3",
    parent_id: "134",
  },
  {
    id: "463",
    title: "Những điều khuyến khích của lễ nguyện Salah",
    hadeeths_count: "2",
    parent_id: "134",
  },
  {
    id: "464",
    title: "Về nghi thức Salah",
    hadeeths_count: "2",
    parent_id: "134",
  },
  {
    id: "465",
    title: "Các lời tụng niệm của lễ nguyện Salah",
    hadeeths_count: "2",
    parent_id: "134",
  },
  {
    id: "467",
    title: "Các lỗi mắc phải của người dâng lễ nguyện Salah",
    hadeeths_count: "1",
    parent_id: "134",
  },
  {
    id: "468",
    title: "Sujud Sahu, Sujud xướng đọc và Sujud tạ ơn",
    hadeeths_count: "1",
    parent_id: "134",
  },
  {
    id: "469",
    title: "Ân phúc của lễ nguyện Salah tập thể và các giáo luật liên quan",
    hadeeths_count: "2",
    parent_id: "134",
  },
  {
    id: "470",
    title: "Giáo luật về Imam và người theo sau",
    hadeeths_count: "5",
    parent_id: "134",
  },
  {
    id: "471",
    title: "Lễ nguyện Salah dành cho người gặp trở ngại",
    hadeeths_count: "2",
    parent_id: "134",
  },
  {
    id: "472",
    title: "Lễ nguyện Salah thứ sáu",
    hadeeths_count: "2",
    parent_id: "134",
  },
  {
    id: "473",
    title: "Lễ nguyện Salah tự nguyện",
    hadeeths_count: "7",
    parent_id: "134",
  },
  {
    id: "484",
    title: "Qiyamu-lail (lễ nguyện Salah trong đêm)",
    hadeeths_count: "7",
    parent_id: "473",
  },
  {
    id: "492",
    title: "Cái chết và các giáo luật liên quan",
    hadeeths_count: "4",
    parent_id: "135",
  },
  {
    id: "493",
    title: "Tắm cho người chết",
    hadeeths_count: "2",
    parent_id: "135",
  },
  {
    id: "495",
    title: "Cách thức lễ nguyện Salah cho người chết",
    hadeeths_count: "1",
    parent_id: "135",
  },
  {
    id: "497",
    title: "Chia buồn",
    hadeeths_count: "2",
    parent_id: "135",
  },
  {
    id: "500",
    title: "Tính bắt buộc của Zakah và giới luật cho người không chấp hành",
    hadeeths_count: "1",
    parent_id: "136",
  },
  {
    id: "503",
    title: "Giáo luật Zakah và các vấn đề liên quan",
    hadeeths_count: "1",
    parent_id: "136",
  },
  {
    id: "509",
    title: "Zakah Al-Fit-ri",
    hadeeths_count: "1",
    parent_id: "136",
  },
  {
    id: "510",
    title: "Cách chi của Zakah",
    hadeeths_count: "1",
    parent_id: "136",
  },
  {
    id: "511",
    title: "Từ thiện",
    hadeeths_count: "13",
    parent_id: "136",
  },
  {
    id: "513",
    title: "Ân phúc nhịn chay",
    hadeeths_count: "2",
    parent_id: "137",
  },
  {
    id: "514",
    title: "Những khuyến khích của nhịn chay",
    hadeeths_count: "1",
    parent_id: "137",
  },
  {
    id: "517",
    title: "Nhịn chay bù",
    hadeeths_count: "1",
    parent_id: "137",
  },
  {
    id: "532",
    title: "Ân phúc của hành hương Hajj và 'Umrah",
    hadeeths_count: "2",
    parent_id: "138",
  },
  {
    id: "550",
    title: "Giết tế và các hình thức chuộc lỗi khi sai phạm",
    hadeeths_count: "1",
    parent_id: "138",
  },
  {
    id: "551",
    title: "Giết tế",
    hadeeths_count: "1",
    parent_id: "138",
  },
  {
    id: "554",
    title: "Giáo luật hành hương Hajj, 'Umrah và các vấn đề liên quan",
    hadeeths_count: "11",
    parent_id: "138",
  },
  {
    id: "556",
    title: "Ân phúc đấu tranh vì chính nghĩa của Allah",
    hadeeths_count: "13",
    parent_id: "139",
  },
  {
    id: "558",
    title:
      "Giáo luật đấu tranh vì chính nghĩa của Allah và các vấn đề liên quan",
    hadeeths_count: "4",
    parent_id: "139",
  },
  {
    id: "559",
    title: "Phép tắc đấu tranh vì chính nghĩa của Allah",
    hadeeths_count: "4",
    parent_id: "139",
  },
  {
    id: "581",
    title: "Đời sống vợ chồng",
    hadeeths_count: "2",
    parent_id: "191",
  },
  {
    id: "586",
    title: "Li hôn được phép quay lại và ly hôn mãi mãi",
    hadeeths_count: "1",
    parent_id: "192",
  },
  {
    id: "607",
    title: "Mối quan hệ giữa nam và nữ",
    hadeeths_count: "3",
    parent_id: "205",
  },
  {
    id: "636",
    title: "Các lời nói bị cấm và việc gây tổn thương bằng chiếc lưỡi",
    hadeeths_count: "4",
    parent_id: "287",
  },
  {
    id: "640",
    title:
      "Trang phục của Thiên Sứ Muhammad - cầu xin Allah ban bình an và phúc lành cho Người -",
    hadeeths_count: "1",
    parent_id: "406",
  },
  {
    id: "642",
    title:
      "Thức ăn, đồ uống của Thiên Sứ Muhammad - cầu xin Allah ban bình an và phúc lành cho Người -",
    hadeeths_count: "2",
    parent_id: "406",
  },
  {
    id: "645",
    title:
      "Các chuyến đi xa của Thiên Sứ Muhammad - cầu xin Allah ban bình an và phúc lành cho Người -",
    hadeeths_count: "1",
    parent_id: "406",
  },
  {
    id: "646",
    title: "Nhân cách và đạo đức",
    hadeeths_count: "10",
    parent_id: "406",
  },
  {
    id: "647",
    title:
      "Đường lối của Nabi Muhammad - cầu xin Allah ban bình an và phúc lành cho Người -",
    hadeeths_count: "7",
    parent_id: "406",
  },
  {
    id: "648",
    title:
      "Sự rộng lượng của Thiên Sứ Muhammad - cầu xin Allah ban bình an và phúc lành cho Người -",
    hadeeths_count: "4",
    parent_id: "646",
  },
  {
    id: "652",
    title:
      "Sự dịu dàng của Thiên Sứ Muhammad - cầu xin Allah ban bình an và phúc lành cho Người -",
    hadeeths_count: "1",
    parent_id: "646",
  },
  {
    id: "654",
    title:
      "Lòng nhân từ của Thiên Sứ Muhammad - cầu xin Allah ban bình an và phúc lành cho Người -",
    hadeeths_count: "1",
    parent_id: "646",
  },
  {
    id: "659",
    title:
      "Lòng thương người của Thiên Sứ Muhammad - cầu xin Allah ban bình an và phúc lành cho Người -",
    hadeeths_count: "1",
    parent_id: "646",
  },
  {
    id: "662",
    title:
      "Lòng nhẫn nại của Thiên Sứ Muhammad - cầu xin Allah ban bình an và phúc lành cho Người -",
    hadeeths_count: "1",
    parent_id: "646",
  },
  {
    id: "666",
    title:
      "Sự hướng dẫn của Thiên Sứ Muhammad - cầu xin Allah ban bình an và phúc lành cho Người - trong thuyết giảng",
    hadeeths_count: "2",
    parent_id: "647",
  },
  {
    id: "667",
    title:
      "Đường lối của Thiên Sứ Muhammad - cầu xin Allah ban bình an và phúc lành cho Người - trong việc tẩy rửa",
    hadeeths_count: "1",
    parent_id: "647",
  },
  {
    id: "668",
    title:
      "Sự hướng dẫn của Thiên Sứ Muhammad - cầu xin Allah ban bình an và phúc lành cho Người - trong lễ nguyện Salah",
    hadeeths_count: "3",
    parent_id: "647",
  },
  {
    id: "721",
    title: "Các giáo luật và lễ nghĩa 'Eid",
    hadeeths_count: "1",
    parent_id: "415",
  },
  {
    id: "725",
    title: "Các giáo luật về Masjid",
    hadeeths_count: "6",
    parent_id: "134",
  },
  {
    id: "727",
    title: "Lau vuốt lên giày, vớ",
    hadeeths_count: "4",
    parent_id: "133",
  },
  {
    id: "735",
    title: "Đặc điểm của Thiên Sứ Muhammad",
    hadeeths_count: "4",
    parent_id: "367",
  },
];
